apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: 19_use_persistent_volumes
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: "/data"
          name: my-local-storage
  volumes:
    - name: my-local-storage
      persistentVolumeClaim:
        claimName: local-pvc
