apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: myjob
        image: 11_first_job
        imagePullPolicy: Never
      restartPolicy: Never
