apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  my-secret: dmVsdHplcgo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret 
  restartPolicy: Never
  containers:
    - name: dotfile-test-container
      image: bash
      command:
        - "sleep" 
        - "3600"
      #  - "cat" 
      #  - "/mnt/secret-volume/my-secret"
      volumeMounts:
        - name: secret-volume
          mountPath: "/mnt/secret-volume"
          # readOnly: true
