apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 02_pods_with_service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: app
spec:
  selector:
    app: app
  # this is the default
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
