apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      hostNetwork: true
      containers:
      - name: app
        image: 02_pull_from_local_docker
        imagePullPolicy: Never
        ports:
        - containerPort: 80
