apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      hostNetwork: true
      containers:
        - name: app
          image: 03_use_your_own_image
          imagePullPolicy: Never
          ports:
          - containerPort: 80
