apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      hostNetwork: true
      containers:
      - name: app
        image: 03_create_my_image_run_it_and_see_logs
        imagePullPolicy: Never
        ports:
        - containerPort: 80
